export const MOCK_ADMIN_QUEUE = [
  {
    id: 'mock-001',
    lat: 13.756, lng: 100.501,
    province: 'กรุงเทพมหานคร', district: 'บางกอกน้อย',
    road_name: 'ถ.จรัญสนิทวงศ์', status: 'ai_processed',
    image_path: '/mock-crack-1.jpg',
    reported_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    crack_type: 'alligator', severity: 'critical', confidence: 0.924,
  },
  {
    id: 'mock-002',
    lat: 18.796, lng: 98.982,
    province: 'เชียงใหม่', district: 'เมืองเชียงใหม่',
    road_name: 'ถ.นิมมานเหมินทร์', status: 'ai_processed',
    image_path: '/mock-crack-2.jpg',
    reported_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    crack_type: 'pothole', severity: 'high', confidence: 0.871,
  },
  {
    id: 'mock-003',
    lat: 16.432, lng: 102.832,
    province: 'ขอนแก่น', district: 'เมืองขอนแก่น',
    road_name: 'ถ.มิตรภาพ', status: 'under_review',
    image_path: '/mock-crack-3.jpg',
    reported_at: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    crack_type: 'longitudinal', severity: 'medium', confidence: 0.762,
  },
  {
    id: 'mock-004',
    lat: 7.881, lng: 98.398,
    province: 'ภูเก็ต', district: 'กะทู้',
    road_name: 'ถ.เจ้าฟ้า', status: 'ai_processed',
    image_path: '/mock-crack-4.jpg',
    reported_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    crack_type: 'transverse', severity: 'high', confidence: 0.836,
  },
  {
    id: 'mock-005',
    lat: 14.973, lng: 102.101,
    province: 'นครราชสีมา', district: 'เมืองนครราชสีมา',
    road_name: 'ถ.มิตรภาพ (โคราช)', status: 'ai_processed',
    image_path: '/mock-crack-5.jpg',
    reported_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    crack_type: 'block_crack', severity: 'medium', confidence: 0.683,
  },
  {
    id: 'mock-006',
    lat: 13.361, lng: 100.984,
    province: 'ชลบุรี', district: 'ศรีราชา',
    road_name: 'ถ.สุขุมวิท (ชลบุรี)', status: 'under_review',
    image_path: '/mock-crack-6.jpg',
    reported_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    crack_type: 'edge_crack', severity: 'low', confidence: 0.591,
  },
]

export const MOCK_ADMIN_STATS = {
  total: 142,
  pending: 18,
  ai_processed: 34,
  under_review: 9,
  verified: 67,
  rejected: 12,
  resolved: 2,
  by_crack_type: {
    alligator: 28,
    pothole: 22,
    longitudinal: 19,
    transverse: 15,
    edge_crack: 11,
    block_crack: 9,
  },
}
